name: Tests

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: 'Install from rust-toolchain.toml'
        run: rustup show
      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2.7.7
        with:
          cache-on-failure: true
      - name: "Add LLVM Tools Preview"
        run: rustup component add llvm-tools-preview
      - uses: taiki-e/install-action@a209ff0ce0349f9e7cadc4ba8f6a415c8d3b0813 # v2.49.11
        with:
          tool: cargo-nextest,cargo-llvm-cov
      - name: 'Run tests with coverage'
        run: |
          cargo llvm-cov nextest --lcov --output-path lcov.info
