name: Tests

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: 'Install from rust-toolchain.toml'
        run: rustup show
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
        with:
          cache-on-failure: true
      - name: "Add LLVM Tools Preview"
        run: rustup component add llvm-tools-preview
      - uses: taiki-e/install-action@f63c33fd96cc1e69a29bafd06541cf28588b43a4 # v2.58.21
        with:
          tool: cargo-nextest,cargo-llvm-cov
      - name: 'Run tests with coverage'
        # Generate separate reports for nextest and doctests, and combine them.
        run: |
          cargo llvm-cov --no-report nextest --workspace --ignore-filename-regex "(mock|example)/*"
          # cargo llvm-cov --no-report --doc
          cargo llvm-cov report --doctests --lcov --output-path lcov.info --ignore-filename-regex "(mock|example)/*"
      - name: Upload coverage data to codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
